# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Dir
version:      1.02
version_from: lib/LEOCHARRE/Dir.pm
installdirs:  site
requires:
    Cwd:                           3
    Exporter:                      5
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
